%YAML:1.0

# KITTI Datset directory
datasetDir: ../dataset/Kitti/sequences/05

# Camera Intrinsics
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

numFeatures: 150
numFeaturesInit: 50
numFeaturesTracking: 50